application:
  couchbase:
    cluster:
      url: "http://couch:8091"
#      url: "http://localhost:8091"
      username: "admin"
      password: "admin123"
      node: "couch"
#      node: "localhost"
    bucket:
      name: "DataObject"
      quota: 500
    timeout: 10000
    kvTimeout: 3000
    bufferSize: 131072
  parallelism: 10
  datafile: "data.txt"


logging:
  level:
    org.springframework: DEBUG
    com.yevhenii.service: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: logs/application.log
