application:
  couchbase:
    cluster:
      url: "http://couch:8091"
      username: "admin"
      password: "admin123"
      node: "couch"
    bucket: "DataObject"
    timeout: 10000
    kvTimeout: 3000
    bufferSize: 131072
  parallelism: 10
  datafile: "data.txt"
  pageSize: 1000
