application:
  couchbase:
    cluster:
      url: "http://localhost:8091"
#      url: "http://couch:8091"
      username: "admin"
      password: "admin123"
      node: "localhost"
#      node: "couch"
    bucket:
      name: "DataObject"
      quota: 500
    timeout: 10000
    kvTimeout: 3000
    bufferSize: 131072
  parallelism: 10
  datafile: "data.txt"
  pageSize: 1000
